#server:
#  context-path: /phone-api

spring:
  application:
    env: none
    name: phonenumber-api
  main:
    web-application-type: reactive
  jackson:
    property-naming-strategy: SNAKE_CASE
  r2dbc:
    url: r2dbc:h2:file:///./tmp/h2db/belong_${spring.application.env}_db;
    username: sa
    password:
  flyway:
    url: jdbc:h2:file:./tmp/h2db/belong_${spring.application.env}_db;
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    baseline-on-migrate: true
    locations: classpath:db/migration/schema,classpath:db/migration/data/${spring.application.env}
  cache:
    type: caffeine
  caffeine:
    spec: maximumSize=1000,expireAfterAccess=600s

logging:
  level:
    org.springframework:
      web: DEBUG
      validation: DEBUG

